### ISSUE TITLE
Typo: AsynResult

### ISSUE THREAD

**Issue by stakx** [wswind/lightwind#1]
Just a quick head's up about two typos I spotted &mdash; fixing those would obviously be a breaking change as they affect the public API:

https://github.com/wswind/lightwind/blob/781241108e8209409b1d1c9301ab77b3d5e9716d/src/Lightwind.AsyncInterceptor/AsyncInterceptorBase.cs#L43

https://github.com/wswind/lightwind/blob/781241108e8209409b1d1c9301ab77b3d5e9716d/src/Lightwind.AsyncInterceptor/AsyncInterceptorBase.cs#L57

Nice library btw.! :-)

**Comment by wswind** [comment]
I didn't notice this problem.Thanks very much for the review.
